### ISSUE TITLE
将lookup 查找回调改成以ID获取的会更加完美。

### ISSUE THREAD

**Issue by IBOXLAB** [JZaaa/BJUI#1]
$box.find(':input').each(function() {
                var $input = $(this), inputName = $input.attr('id')?$input.attr('id'):$input.attr('name') /*改动优先用ID赋值
一条数据多个信息单元格会自动填充。

**Comment by JZaaa** [comment]
框架非iframe框架，正常情况下应该避免过多的使用id。

现在的lookup组件回调已经有很多方式了，基本上满足了绝大多数需求。如果有特殊需求的话建议用jQuery方法手动实例化lookup组件，再利用回调实现相应功能。
