### ISSUE TITLE
关闭当前标签并刷新列表页

### ISSUE THREAD

**Issue by IBOXLAB** [JZaaa/BJUI#2]
protected function mtReturn($status,$info,$navTabId="",$closeCurrent=true) {
       
	    $udata['id']=session('uid');
        $udata['update_time']=time();
        $Rs=M("user")->save($udata);
        $dat['username'] = session('username');
        $dat['content'] = $info;
		$dat['os']=$_SERVER['HTTP_USER_AGENT'];
        $dat['url'] = U();
        $dat['addtime'] = date("Y-m-d H:i:s",time());
        $dat['ip'] = get_client_ip();
        M("log")->add($dat);
	   
	    
	    $result = array();
        $result['statusCode'] = $status; 
        $result['message'] = $info;
		$result['closeCurrent'] =$closeCurrent;
		if($navTabId!==''){
		 $result['tabid'] = strtolower($navTabId).'/index';	
		}else{
			$result['tabid'] = '';
		}
		
        $result['forward'] = '';
		$result['forwardConfirm']='';
        
        if (empty($type))
            $type = C('DEFAULT_AJAX_RETURN');
        if (strtoupper($type) == 'JSON') {
            // 返回JSON数据格式到客户端 包含状态信息
            header("Content-Type:text/html; charset=utf-8");
            exit(json_encode($result,true));
        } elseif (strtoupper($type) == 'XML') {
            // 返回xml格式数据
            header("Content-Type:text/xml; charset=utf-8");
            exit(xml_encode($result));
        } elseif (strtoupper($type) == 'EVAL') {
            // 返回可执行的js脚本
            header("Content-Type:text/html; charset=utf-8");
            exit($data);
        } else {
            // TODO 增加其它格式
        }
	}
原版本操作成功直接关闭标签页。
当发送"closeCurrent" = true时关闭标签页，不起作用。

**Comment by JZaaa** [comment]
能否提供具体的情景与返回的json数据？

**Comment by IBOXLAB** [comment]
我的EMALI：254281818@qq.com
我给你发源码。你应该会PHP吧.

**Comment by JZaaa** [comment]
可以发送 至 2509642078@qq.com 这个邮箱，或者方便提供线上地址也可以，主要是确定你的使用情景和回调代码，因为这一套系统我也是用于生产环境的，暂时没有出现过上述问题
