### ISSUE TITLE
请教 navtab 切换是 如何重新载入刷新新页面

### ISSUE THREAD

**Issue by YouthguyZ** [JZaaa/BJUI#3]
你好，我想请教下 我想再 点击切换 navtab 导航标签时 重新载入刷新页面  应该使用如何的方法 想修改源码 。

**我现在打开新标签使用BJUI.navtab({id:"时间戳生产",title:"影像查看",url:"./firstImg.html?_=时间戳"})  打开多个 navtab 页面共用一个html 然后切换 navtab 时 就是不知道如何写 切换时的触发事件 去 刷新已经打开的 菜单标签页面**

- 效果视频

https://github.com/user-attachments/assets/c95f9b94-3779-482f-9c02-97ecc5df01b6

- 代码区域找到了 
![Snipaste_2024-09-13_14-30-09](https://github.com/user-attachments/assets/8cf67c65-9a09-4cdd-8071-3edd013d5e78)

- 方法看到了 不知道如何使用
![Snipaste_2024-09-13_14-34-59](https://github.com/user-attachments/assets/7e6d7b9d-63c8-4d72-af0e-78a0f92ac407)

**Comment by JZaaa** [comment]
暂时没有点击标签的返回事件，但是你可以自己实现.
在全局监听标签点击事件，获取到标签data中存储的navtabId，进行手动刷新navtab,试一下这样是否满足你的需要
```javascript
  $(document).on('click', '#bjui-navtab>.tabsPageHeader .nav-tabs li, #bjui-navtab .tabsMoreList li', function (e) {
    let $that = $(this)
    if ($that.parent().hasClass('tabsMoreList')) {
      $that = $('#bjui-navtab>.tabsPageHeader .nav-tabs li').eq($that.index())
    }
    const tagOptions = $that.data() || {}
    if (tagOptions.initOptions && tagOptions.initOptions.id) {
      $that.navtab('refresh', tagOptions.initOptions.id)
    }
  })
```

**Comment by YouthguyZ** [comment]
我再 switchTab 这个切换 标签 方法里面 可以获取 id 可以直接操作 去刷新 $that.navtab('refresh', tagOptions.initOptions.id) 这个可以嘛  这个刷新的方法作用是重新加载页面嘛 像第一次 openTab 一样吗 加载 html js 重新 new 一个 **Vue** 对象 refresh 和 reload 那个功能实现更好

**Comment by JZaaa** [comment]
- switchTab方法获取ID在进行刷新也是可以的，但是这个是navtab内部方法，没有其他定制化需求不太建议修改框架的方法
- **refresh**实现也是调用了**reload**，但是**refresh**复用了上一次navtab的参数，如果参数需要改变应调用reload，否则应调用refresh
- 不论**refresh**还是**reload**都是通过ajax重新请求页面数据，对绑定Navtab内部DOM的Vue 都可以使用无差别

**Comment by JZaaa** [comment]
需要注意在navtab/dialog上监听的全局dom事件或者定时器等在刷新或关闭dialog/navtab后不会清除，需要手动处理，否则刷新会重复定义事件，所以上面的代码示例应加在BJUI框架初始化代码下面，而不是navtab里。

另外框架与Vue混用除了要解决jQuery组件与Vue冲突的问题，还需要注意需要注意**Vue2**在navtab/dialog重载后正常不会触发**beforeDestroy**生命周期，在``v1.7.4+``后在Vue实例化DOM上增加 ``[data-bj-vue-dom]`` 属性就可以触发了，Vue3在``v1.7.4+``后``onBeforeUnmount``这些生命周期自动触发。

这个框架引入Vue混用问题不大，我自己在实际生产中也是引入Vue，有时候感觉处理与jQuery插件的冲突太麻烦也直接引入了element-ui，写一些样式兼容基本上完美使用

**Comment by YouthguyZ** [comment]
> 暂时没有点击标签的返回事件，但是你可以自己实现. 在全局监听标签点击事件，获取到标签data中存储的navtabId，进行手动刷新navtab,试一下这样是否满足你的需要
> 
> ```js
>   $(document).on('click', '#bjui-navtab>.tabsPageHeader .nav-tabs li, #bjui-navtab .tabsMoreList li', function (e) {
>     let $that = $(this)
>     if ($that.parent().hasClass('tabsMoreList')) {
>       $that = $('#bjui-navtab>.tabsPageHeader .nav-tabs li').eq($that.index())
>     }
>     const tagOptions = $that.data() || {}
>     if (tagOptions.initOptions && tagOptions.initOptions.id) {
>       $that.navtab('refresh', tagOptions.initOptions.id)
>     }
>   })
> ```


- 用了这个监听事件处理 也加在BJUI框架初始化代码下面了 

- 当我切换navtab页签的时候  打开的相同url路径不同拼接参数的地址 类似url:"./firstImg.html?_=时间戳"  navtab打开页签后 点击切换 和其他地址不同的页签之间切换没有问题会刷新 
- 当点击相同路径不同参数共用地址的页签时 **refresh** 方法会把 另一个最新打开的页签值数据载入到点击中的navtab页签中，我看的选中当前 navtabid 时取得也是选中的 不知道为何加载的不是本navtab页签的数据

**Comment by JZaaa** [comment]
需要确定navtab的ID是否重复，ztree方式实例化时候navtabId指定的是 data-tabid
```
 <li data-id="11" data-pid="1" data-url="form-input.html?query=first" data-tabid="不可重复" ...>文本框
</li>
<li data-id="11-second" data-pid="1" data-url="form-input.html?query=second" data-tabid="不可重复" ...>文本框1</li>
```


![CPT2409141606-573x354](https://github.com/user-attachments/assets/62f1f225-9329-4f1b-bfb1-8b6af60b48c8)

**Comment by YouthguyZ** [comment]
> 需要确定navtab的ID是否重复，ztree方式实例化时候navtabId指定的是 data-tabid
> 
> ```
>  <li data-id="11" data-pid="1" data-url="form-input.html?query=first" data-tabid="不可重复" ...>文本框
> </li>
> <li data-id="11-second" data-pid="1" data-url="form-input.html?query=second" data-tabid="不可重复" ...>文本框1</li>
> ```
> 
> ![CPT2409141606-573x354](https://private-user-images.githubusercontent.com/26134251/367499483-62f1f225-9329-4f1b-bfb1-8b6af60b48c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIxNzgsIm5iZiI6MTcyNjMwMTg3OCwicGF0aCI6Ii8yNjEzNDI1MS8zNjc0OTk0ODMtNjJmMWYyMjUtOTMyOS00ZjFiLWJmYjEtOGI2YWY2MGI0OGM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTBjMGY3ZGM1ZTJiYmNiODdhNDQ3ZDBkMTEyNTk3Mjk4NmY0ZDU5MjVmMzBiNWMzYjdjNDgxNDExZjkwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ny1RvHLKfthoEuQmG_MOXwvjv7M-27Z2KrIu2XLALF8) [ ![CPT2409141606-573x354](https://private-user-images.githubusercontent.com/26134251/367499483-62f1f225-9329-4f1b-bfb1-8b6af60b48c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIxNzgsIm5iZiI6MTcyNjMwMTg3OCwicGF0aCI6Ii8yNjEzNDI1MS8zNjc0OTk0ODMtNjJmMWYyMjUtOTMyOS00ZjFiLWJmYjEtOGI2YWY2MGI0OGM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTBjMGY3ZGM1ZTJiYmNiODdhNDQ3ZDBkMTEyNTk3Mjk4NmY0ZDU5MjVmMzBiNWMzYjdjNDgxNDExZjkwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ny1RvHLKfthoEuQmG_MOXwvjv7M-27Z2KrIu2XLALF8) ](https://private-user-images.githubusercontent.com/26134251/367499483-62f1f225-9329-4f1b-bfb1-8b6af60b48c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIxNzgsIm5iZiI6MTcyNjMwMTg3OCwicGF0aCI6Ii8yNjEzNDI1MS8zNjc0OTk0ODMtNjJmMWYyMjUtOTMyOS00ZjFiLWJmYjEtOGI2YWY2MGI0OGM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTBjMGY3ZGM1ZTJiYmNiODdhNDQ3ZDBkMTEyNTk3Mjk4NmY0ZDU5MjVmMzBiNWMzYjdjNDgxNDExZjkwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ny1RvHLKfthoEuQmG_MOXwvjv7M-27Z2KrIu2XLALF8) [ ](https://private-user-images.githubusercontent.com/26134251/367499483-62f1f225-9329-4f1b-bfb1-8b6af60b48c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIxNzgsIm5iZiI6MTcyNjMwMTg3OCwicGF0aCI6Ii8yNjEzNDI1MS8zNjc0OTk0ODMtNjJmMWYyMjUtOTMyOS00ZjFiLWJmYjEtOGI2YWY2MGI0OGM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTBjMGY3ZGM1ZTJiYmNiODdhNDQ3ZDBkMTEyNTk3Mjk4NmY0ZDU5MjVmMzBiNWMzYjdjNDgxNDExZjkwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ny1RvHLKfthoEuQmG_MOXwvjv7M-27Z2KrIu2XLALF8)


> 我新建选项卡的时候 **BJUI.navtab({id:"Date.now()时间戳",title:"影像查看",url:"./firstImg.html?_=时间戳"})**  navtab id 是唯一的 用的时间戳生成的 我给您发邮件了 有一个操作视频 麻烦您了 指教一下小弟🥲

**Comment by JZaaa** [comment]
已回复邮件
