### ISSUE TITLE
新建标签的处理逻辑

### ISSUE THREAD

**Issue by YouthguyZ** [JZaaa/BJUI#4]
- 触发新建标签打开新页签处理逻辑，Jz哥，我想再打开新标签的时候判断 如果options.title 为某个指定的标题如‘流程任务’时 发送请求然后判断 将此条options.url修改为符合条件的页面的 html路径 并将这个接口加 5秒的定时函数 这个地方的操作合适嘛 或者有其他的触发方法嘛 请教一下

- 
![Snipaste_2024-09-26_13-31-11](https://github.com/user-attachments/assets/4538853b-be51-4242-97fc-2a78277a1570)

- 
![微信图片_20240926135158](https://github.com/user-attachments/assets/e342734e-570d-45ec-85d6-6cf53c0d3830)

**Comment by JZaaa** [comment]
这个情况你可以封装一个打开dialog方法呀，如果要符合条件就打开符合条件的html，否则走默认逻辑。
或者你可以首先打开一个空内容的dialog，通过 ``onLoad``或者在dialog内进行title比对，渲染页面可以通过``ajaxload``异步加载页面，定时刷新ajaxload就行了
